### ISSUE TITLE
Endless starting ClamAV daemon

### ISSUE THREAD

**Issue by normaliok** [evild3ad/MemProcFS-Analyzer#11]
All looks normal until the step "Starting ClamAV Daemon" when I get endless connection attempts  to 127.0.0.1
![Снимок экрана 2022-07-18 164111](https://user-images.githubusercontent.com/35446022/179524761-75e48cea-a2fa-4961-9256-c979a45bb883.jpg)

**Comment by evild3ad** [comment]
You need to install and configure ClamAV manually. Please check README.md for further instructions.

At the end of the MemProcFS-Analyzer.ps1 you find the "Main" where you can enable/disable features. 
You can disable "ClamAVUpdate" and "ClamAV" if needed and scan "X:\name" e.g. with Microsoft Defender AntiVirus (if you prefer).

Please let me know if you have still any issues.

**Comment by evild3ad** [comment]
Closed.
