### ISSUE TITLE
Not executing

### ISSUE THREAD

**Issue by archanchoudhury** [evild3ad/MemProcFS-Analyzer#12]
Hi There,
Thanks a lot for creating such an awesome tool. While running, it is throwing below error- 

```[Error] github.com is NOT reachable. Please check your network connection and try again.```

My internet connection is working fine. Could you please let me know how to resolve this issue?
![image](https://user-images.githubusercontent.com/51078911/194907765-ce54edf4-4ce4-4808-8f69-024e2e70921b.png)

**Comment by evild3ad** [comment]
Hi, it seems that github.com is not reachable. Are you using VPN or a proxy?

**Comment by archanchoudhury** [comment]
No I am not using any VPN or proxy. I have removed the check from the script and it is running now. I believe, it is due to PingException at the github end. Probably you can give a test to google.com to see if the machine has internet connection or not.

![image](https://user-images.githubusercontent.com/51078911/194910155-eac1f955-1f6d-45f8-9bfc-468eebfb3a36.png)

![image](https://user-images.githubusercontent.com/51078911/194910305-653778fa-3bb9-4fea-a867-92415e89b44c.png)

**Comment by evild3ad** [comment]
Which PowerShell version are you using?

**Comment by evild3ad** [comment]
Is this command working on your side?

`if ((Test-NetConnection -ComputerName github.com -Port 443).TcpTestSucceeded) { Write-Output "True" }`

**Comment by evild3ad** [comment]
Will be fixed with the next version. Thanks for reporting!

**Comment by archanchoudhury** [comment]
Also one more thing.. I noticed the script is exited on a Dokan Check at the very beginning even before selecting the memory image. So, you might wanna tweak the logic to install the dependencies first and then put the option to select the image file. I have installed the Dokan explicitly on first run.
