### ISSUE TITLE
Test-Connection: [Error] github.com is NOT reachable.

### ISSUE THREAD

**Issue by Bloggzy** [evild3ad/MemProcFS-Analyzer#15]
I've found that a number of features in v0.6 are being hampered by this error:

`[Error] github.com is NOT reachable...`

Github.com is in fact reachable, but the test-connection is failing for some reason?

To replicate, I ran: 

`Test-Connection -ComputerName github.com -Count 1 -Quiet`

I tried this from a number of different computers, and get a "false" returned from all of them. Where as something like:

`Test-Connection -ComputerName google.com -Count 1 -Quiet`

Returns "true".

Not sure what the cause is, but some parts of the script are not currently working, as they're failing this connection test.

**Comment by evild3ad** [comment]
Yea...it's a strange behaviour. In my region it working perfectly. I've updated this already for v0.7. It's only the github.com check.

Please let me know how the new command works on your side:
`((Test-NetConnection -ComputerName github.com -Port 443).TcpTestSucceeded)`

Thank you!

**Comment by Bloggzy** [comment]
It is strange behaviour, I'm unsure what's causing it, but I did test it on three different systems with three different IP addresses and had the same issue with each.

I just tested your new test and it appears to work as intended:

`PS C:\> ((Test-NetConnection -ComputerName github.com -Port 443).TcpTestSucceeded)
True
PS C:\> Test-Connection -ComputerName github.com -Count 1 -Quiet
False
PS C:\>   `

**Comment by evild3ad** [comment]
Nice! Thank you!

```
# Check if GitHub is reachable
if (!(Test-NetConnection -ComputerName github.com -Port 443).TcpTestSucceeded)
{
          Write-Host "[Error] github.com is NOT reachable. Please check your network connection and try again." -ForegroundColor Red
          $Host.UI.RawUI.WindowTitle = "$DefaultWindowsTitle"
          Exit
}
```
