### ISSUE TITLE
ClamAV: on-screen messages point to old ClamAV URL?

### ISSUE THREAD

**Issue by Bloggzy** [evild3ad/MemProcFS-Analyzer#16]
If either of the following ClamAV conf files are missing, the on-screen user feedback points the user to a URL that is possibly out of date?

Example, if either of these events happen:
- [Error] freshclam.conf is missing. (Line 4931)
- [Error] clamd.conf is missing. (Line: 4941)

Then the user gets a message on screen, pointing them to this URL:
"https://www.clamav.net/documents/installing-clamav-on-windows --> First Time Set-Up"

But that URL, redirects to the main ClamAV docs site (https://docs.clamav.net/) and isn't very helpful. A better URL to display would be:
"https://docs.clamav.net/manual/Usage/Configuration.html#windows" ?

This URL is referenced in the script comments, so you may wish to update the console messages to point to the same URL as well?

**Comment by evild3ad** [comment]
Thanks for the hint! I updated both URLs in the script region ClamAVUpdate.
