### ISSUE TITLE
ClamAV errors "WARNING: File path check failure"

### ISSUE THREAD

**Issue by tuttimann** [evild3ad/MemProcFS-Analyzer#20]
Hi, I am getting many ClamAV errors "WARNING: File path check failure".
Didn't I configure ClamAV correctly?

![clamav](https://user-images.githubusercontent.com/35948670/214003866-41ee30b6-0720-4b9a-b0e0-6bdcf9cd54c1.png)

**Comment by evild3ad** [comment]
I see these warnings, too. Should be fine!

**Comment by tuttimann** [comment]
Thanks for the answer.
