### ISSUE TITLE
frozen on - [Info]  Processing C:\Users\Admin\Downloads\MemProcFS-Analyzer-v0.9\MemProcFS-Analyzer-v0.9\ch2.dmp [approx. 1-10 min]

### ISSUE THREAD

**Issue by madeonukraine** [evild3ad/MemProcFS-Analyzer#23]
C:\Users\Admin\Downloads\MemProcFS-Analyzer-v0.9\MemProcFS-Analyzer-v0.9\MemProcFS-Analyzer.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): 
i write "R" and after 

installed the necessary dependencies that are indicated in your branch, I run the script on behalf of the admin, there is a check for the presence of software, after everything is fine, the program writes that the process will take from 1 to 10 minutes but does not even load the PC, waited 15 hours with a training 500mb RAM dump, as well as my own, tried it on different PCs and clean virtual machines, writes that the disk mount but it is not even in the hard disk manager, tell me what am I doing wrong?

**Comment by evild3ad** [comment]
Hi, please run MemProcFS directly against your memory snapshot and check
for any error message. 500 MB sounds old or bogus.

https://github.com/ufrisk/MemProcFS
