### ISSUE TITLE
Personal IPInfo token present

### ISSUE THREAD

**Issue by wikijm** [evild3ad/MemProcFS-Analyzer#30]
Hi @evild3ad

I wanted to warn you about the fact that you let your personal IPInfo Access Token into your code, on this [line](https://github.com/evild3ad/MemProcFS-Analyzer/blob/6636bab218ae0c6cafc40bce7eb6b7c1111ff6d9/MemProcFS-Analyzer.ps1#L3787C1-L3787C45).

Instead, what do you think of using, as an example, the one provided into the [official documentation](https://ipinfo.io/developers)?

**Comment by wikijm** [comment]
Just added this change proposal into https://github.com/evild3ad/MemProcFS-Analyzer/pull/29

**Comment by evild3ad** [comment]
Hi, thanks for reporting. I will have a look tomorrow and fix everything. It is only a free token...forgot to remove it.

**Comment by evild3ad** [comment]
Yea…and the quota always already used. 😁

**Comment by wikijm** [comment]
Fixed with https://github.com/evild3ad/MemProcFS-Analyzer/commit/845a2dac81999950aa5ba1061025c9f940a1f529 😃
