### ISSUE TITLE
JSON Formatting

### ISSUE THREAD

**Issue by Liebershnitzel** [evild3ad/MemProcFS-Analyzer#32]
Hi, my team typically uses splunk which favors JSON formatting. It would be extremely beneficial to us if you could add a JSON option on top of the CSV option you already provide. Fantastic addition to the already amazing MemProcFS project, thank you for creating this.

**Comment by evild3ad** [comment]
You can use for example the 'FS_Forensic_JSON' output by MemProcFS:
https://github.com/ufrisk/MemProcFS/wiki/FS_Forensic_JSON

It is currently not planned to add JSON formatted output files to the MemProcFS-Analyzer. Sorry!
