### ISSUE TITLE
Backblaze B2 Unreachable

### ISSUE THREAD

**Issue by antmar904** [evild3ad/MemProcFS-Analyzer#38]
Hi
I am getting this error:

`Invoke-WebRequest : {
  "code": "not_found",
  "message": "File with such name does not exist.",
  "status": 404
}
At E:\_Tools\MemProcFS-Analyzer-v1.0\MemProcFS-Analyzer.ps1:1033 char:20
+ ... atusCode = (Invoke-WebRequest -Uri $URL -UseBasicParsing -DisableKeep ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
[Error] f001.backblazeb2.com is NOT reachable. Please check your network connection and try again.`

**Comment by antmar904** [comment]
I think it's trying to fecth:

https://f001.backblazeb2.com/file/EricZimmermanTools/net6/AmcacheParser.zip

**Comment by evild3ad** [comment]
Backblaze had some infrastructure changes / global updates. 

Eric is hosting his tools on his own now. New permanent links. Next MemProcFS release is in the works.
https://download.mikestammer.com/net6/AmcacheParser.zip

**Comment by artafak** [comment]
yes, thanks @evild3ad

for all changes, replace "https://f001.backblazeb2.com/file/EricZimmermanTools" by "https://download.mikestammer.com" in follow lines :

	Line  1032:     $URL = "https://download.mikestammer.com/net6/AmcacheParser.zip"
	Line  1430:     $URL = "https://download.mikestammer.com/net6/AmcacheParser.zip"
	Line  1445:     $URL = "https://download.mikestammer.com/net6/AmcacheParser.zip"
	Line  1504:     $URL = "https://download.mikestammer.com/net6/AppCompatCacheParser.zip"
	Line  1519:     $URL = "https://download.mikestammer.com/net6/AppCompatCacheParser.zip"
	Line  1662:     $URL = "https://download.mikestammer.com/net6/EvtxECmd.zip"
	Line  1677:     $URL = "https://download.mikestammer.com/net6/EvtxECmd.zip"
	Line  2036:     $URL = "https://download.mikestammer.com/net6/RECmd.zip"
	Line  2051:     $URL = "https://download.mikestammer.com/net6/RECmd.zip"
	Line  2110:     $URL = "https://download.mikestammer.com/net6/SBECmd.zip"
	Line  2125:     $URL = "https://download.mikestammer.com/net6/SBECmd.zip"

Have a good day :)

**Comment by evild3ad** [comment]
Thank you! Everything fixed. New release coming soon!
