### ISSUE TITLE
RECmd: Use DFIRBatch.reb, add `--sync` similar to EvtxECmd

### ISSUE THREAD

**Issue by AndrewRathbun** [evild3ad/MemProcFS-Analyzer#41]
FYSA, RECmd has identical `--sync` functionality similar to KAPE, EvtxECmd, and SQLECmd. That being said, the KrollBatch.reb file is no longer being maintained in favor of DFIRBatch.reb, which can be found here: https://github.com/EricZimmerman/RECmd/blob/master/BatchExamples/DFIRBatch.reb

**Comment by evild3ad** [comment]
Thank you! I will switch to DFIRBatch.reb and implement the sync.

**Comment by evild3ad** [comment]
I have added the --sync functionality to RECmd in MemProcFS-Analyzer Updater v0.2 (Updater.ps1) today.

Adding it to MemProcFS-Analyzer.ps1...and switching to DFIRBatch.reb is still pending.

**Comment by evild3ad** [comment]
I finally added the RECmd --sync functionality and the DFIR Batch File. Thanks for reporting! The new version will be released the next days.

**Comment by AndrewRathbun** [comment]
No problem! Very necessary improvements to make, much appreciated.
