### ISSUE TITLE
Multiple errors and ELK not loading

### ISSUE THREAD

**Issue by antmar904** [evild3ad/MemProcFS-Analyzer#44]
Here is the output file
[2024-09-15T145255-memdump.txt](https://github.com/user-attachments/files/17006603/2024-09-15T145255-memdump.txt)

**Comment by RiritoXXL** [comment]
Do you downloaded Dokany File System?!

**Comment by antmar904** [comment]
Yes

**Comment by RiritoXXL** [comment]
okay, maybe it's bug with memprocfs

**Comment by antmar904** [comment]
I got ELK launching now however most of the time I start my memory forensics and walk away.  When I come back I am prompted to enter the Elasticsearch username and password but I can't find it in the powershell windows.  How can I find the username and password?

**Comment by RiritoXXL** [comment]
idk why

**Comment by evild3ad** [comment]
I checked '2024-09-15T145255-memdump.txt'. There is no issue related to Dokany File System.

You can install  Python and add it to the system environment variable or simply disable 'Invoke-1768' in the main at the end of the script. 

It seems that the processing of the web history information is bogus. Nothing I can fix on my side.

Have you read the [Elasticsearch](https://github.com/evild3ad/MemProcFS-Analyzer/wiki/Elasticsearch) page in the Wiki? I tested it a minute ago and it is still working this way.
