### ISSUE TITLE
ClamAV will not run On my Win11

### ISSUE THREAD

**Issue by NomisRenarc** [evild3ad/MemProcFS-Analyzer#45]
Followed the instructions for ClamAV, this is the error I get:

Program 'clamscan.exe' failed to run: The specified executable is not a valid application for this OS platform.

any ideas?
Without this working I cannot use the ClamAV scan options for the memory analysis.

**Comment by evild3ad** [comment]
Have you tried the MSI?

https://www.clamav.net/downloads/production/clamav-1.4.1.win.x64.msi

**Comment by NomisRenarc** [comment]
please excuse my silliness, just noticed I downloaded the arm version instead of x64, corrected and all good now.
