### ISSUE TITLE
Zircolite v2.30.1 not extracting? wait 1 day)

### ISSUE THREAD

**Issue by madeonukraine** [evild3ad/MemProcFS-Analyzer#46]
[Info]  Latest Release: Zircolite v2.30.1 (2024-10-13)
[Info]  Dowloading Latest Release ...
Invoke-WebRequest : Невозможно разрешить удаленное имя: 'github.com'
C:\FRST\1\MemProcFS-Analyzer-v1.1.0\Updater.ps1:1655 знак:5
+     Invoke-WebRequest -Uri $Download -OutFile "$SCRIPT_DIR\Tools\$7Zi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

[Info]  Extracting Files ...

**Comment by madeonukraine** [comment]
all security in Win10 disabled

**Comment by evild3ad** [comment]
Have you checked if the file was successfully downloaded? It looks for me that the download failed. I don't know why...on my side everything works smoothly...tested it on three different machines.

**Comment by evild3ad** [comment]
Zircolite v2.30.1 shows version number v2.30.0...and Zircolite is updated all the time when you you launch 'Updater.ps1'. I created an issue for this.

**Comment by madeonukraine** [comment]
yes it will download, but it will not unpack

**Comment by wagga40** [comment]
Updated the binary and the repo. It should be OK. Sorry.
