### ISSUE TITLE
First run unfinished but no error

### ISSUE THREAD

**Issue by lincion** [evild3ad/MemProcFS-Analyzer#47]
Run PowerShell with Administer
In MemProcFS-Analyzer-v1.1.0\Logs\Updater.txt：

MemProcFS-Analyzer Updater v0.1 - Automated Installer/Updater for MemProcFS-Analyzer
(c) 2024 Martin Willing at Lethal-Forensics (https://lethal-forensics.com/)

Update date: 2024-10-27 08:31:49 UTC

[Info]  Current Version: MemProcFS v5.12.5
[Info]  Latest Release:  MemProcFS v5.12.5 (2024-10-09)
[Info]  You are running the most recent version of MemProcFS.
[Info]  YARA Custom Rules NOT found.

and PowerShell quit at this time.What should I do?

**Comment by evild3ad** [comment]
I will have a look on the Updater.ps1 script tomorrow.

The script checks for the latest update of the YARA custom rules at this point:
`Invoke-WebRequest -Uri "https://raw.githubusercontent.com/evild3ad/yara/main/README.md"`

Verify if the page is reachable and you AV or browser is not blocking it.

**Comment by lincion** [comment]
> I will have a look on the Updater.ps1 script tomorrow.
> 
> The script checks for the latest update of the YARA custom rules at this point: `Invoke-WebRequest -Uri "https://raw.githubusercontent.com/evild3ad/yara/main/README.md"`
> 
> Verify if the page is reachable and you AV or browser is not blocking it.

Thanks for your reply, I can get the page through browser successfully and 
cmd: curl "https://raw.githubusercontent.com/evild3ad/yara/main/README.md" successfully as well
# yara
YARA rules for MemProcFS-Analyzer

<b>Last updated: 2024-08-25</b>

**Comment by evild3ad** [comment]
Than you should see following message on the screen:
`[Info]  Latest Update: 2024-08-25`

**Comment by lincion** [comment]
> Than you should see following message on the screen: `[Info] Latest Update: 2024-08-25`

Update date: 2024-10-27 11:06:31 UTC

[Info]  Current Version: MemProcFS v5.12.5
PS>TerminatingError(Invoke-WebRequest):“{"message":"API rate limit exceeded for 52.195.180.246. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
”
Invoke-WebRequest : {"message":"API rate limit exceeded for 52.195.180.246. (But here's the good news: Authenticated req
uests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.
com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Is there some way to download with github authenticated info?

**Comment by lincion** [comment]
> Than you should see following message on the screen: `[Info] Latest Update: 2024-08-25`

[Info]  Current Version: MemProcFS v5.12.5
[Info]  Latest Release:  MemProcFS v5.12.5 (2024-10-09)
[Info]  You are running the most recent version of MemProcFS.
[Info]  YARA Custom Rules NOT found.

Still above.
And try in same powershell window:
curl "https://raw.githubusercontent.com/evild3ad/yara/main/README.md"

StatusCode        : 200
StatusDescription : OK
Content           : # yara
                    YARA rules for MemProcFS-Analyzer
                    
                    <b>Last updated: 2024-08-25</b>
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
                    Strict-Transport-Security: max-age=31536000
                    X-Content-Type-Options: nosniff
                    ...
Forms             : {}
Headers           : {[Connection, keep-alive], [Content-Security-Policy, default-src 'none'; style-src 'unsafe-inline';
                     sandbox], [Strict-Transport-Security, max-age=31536000], [X-Content-Type-Options, nosniff]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 73

**Comment by evild3ad** [comment]
`# Determining latest update on GitHub`
`$WebRequest = Invoke-WebRequest -Uri "https://raw.githubusercontent.com/evild3ad/yara/main/README.md"`
`$Content = $WebRequest.Content.Split([Environment]::NewLine) | Select-String -Pattern "Last updated:"`
`$Pattern = "[0-9]{4}-[0-9]{2}-[0-9]{2}"`
`$LatestUpdate = [regex]::Matches($Content, $Pattern).Value`
`Write-Output "[Info]  Latest Update: $LatestUpdate"`

Please try line by line.

**Comment by lincion** [comment]
> `# Determining latest update on GitHub` `$WebRequest = Invoke-WebRequest -Uri "https://raw.githubusercontent.com/evild3ad/yara/main/README.md"` `$Content = $WebRequest.Content.Split([Environment]::NewLine) | Select-String -Pattern "Last updated:"` `$Pattern = "[0-9]{4}-[0-9]{2}-[0-9]{2}"` `$LatestUpdate = [regex]::Matches($Content, $Pattern).Value` `Write-Output "[Info] Latest Update: $LatestUpdate"`
> 
> Please try line by line.

I write the code above into text.ps1, and run: ./test.ps1 > output.txt, but it's empty.
And try line by line, powershell just exit immediatly after one command is executed.

**Comment by lincion** [comment]
> `# Determining latest update on GitHub` `$WebRequest = Invoke-WebRequest -Uri "https://raw.githubusercontent.com/evild3ad/yara/main/README.md"` `$Content = $WebRequest.Content.Split([Environment]::NewLine) | Select-String -Pattern "Last updated:"` `$Pattern = "[0-9]{4}-[0-9]{2}-[0-9]{2}"` `$LatestUpdate = [regex]::Matches($Content, $Pattern).Value` `Write-Output "[Info] Latest Update: $LatestUpdate"`
> 
> Please try line by line.

yes I get it.

PS C:\WINDOWS\system32> $WebRequest = Invoke-WebRequest -Uri "https://raw.githubusercontent.com/evild3ad/yara/main/README.md"
$Content = $WebRequest.Content.Split([Environment]::NewLine) | Select-String -Pattern "Last updated:"
$Pattern = "[0-9]{4}-[0-9]{2}-[0-9]{2}"
$LatestUpdate = [regex]::Matches($Content, $Pattern).Value
Write-Output "[Info]  Latest Update: $LatestUpdate"
[Info]  Latest Update: 2024-08-25

**Comment by lincion** [comment]
> `# Determining latest update on GitHub` `$WebRequest = Invoke-WebRequest -Uri "https://raw.githubusercontent.com/evild3ad/yara/main/README.md"` `$Content = $WebRequest.Content.Split([Environment]::NewLine) | Select-String -Pattern "Last updated:"` `$Pattern = "[0-9]{4}-[0-9]{2}-[0-9]{2}"` `$LatestUpdate = [regex]::Matches($Content, $Pattern).Value` `Write-Output "[Info] Latest Update: $LatestUpdate"`
> 
> Please try line by line.

I've succeed, use PowerShell ISE instead of PowerShell can run successfully, but why?

**Comment by evild3ad** [comment]
Have you tried it with Windows PowerShell 5.1 before? ...should be the same with ISE...only some more assemblies are loaded.

**Comment by lincion** [comment]
> Have you tried it with Windows PowerShell 5.1 before? ...should be the same with ISE...only some more assemblies are loaded.

powershell version: 5.1.19041.5007, but it works.
